Window.SetBackgroundTopColor(0.125, 0.133, 0.141);
Window.SetBackgroundBottomColor(0.125, 0.133, 0.141);

logo.image = Image("logo.png");
logo.size = Math.Min(Window.GetWidth(), Window.GetHeight()) * 0.20;
logo.image = logo.image.Scale(logo.size, logo.size);
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
logo.sprite.SetZ(100);
