Net/ThemeName "PiXonyx"
Net/IconThemeName "PiXtrix"
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Gtk/FontName "Nunito Sans Light 12"
Gtk/ToolbarStyle 3
Gtk/ButtonImages 0
Gtk/MenuImages 0
Gtk/CursorThemeSize 24
Gtk/AutoMnemonics 1
Gtk/EnableMnemonics 1
Gtk/ColorScheme "selected_bg_color:#767674747c7c\nselected_fg_color:#f6f6f5f5f4f4\nbar_bg_color:#3d3d3e3e3f3f\nbar_fg_color:#dededddddada\n"
Gtk/CursorThemeName "PiXtrix"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/RGBA "rgb"
