[*]
wallpaper_mode=color
wallpaper_common=1
wallpaper=
desktop_bg=#202022222424
desktop_fg=#dededddddada
desktop_shadow=#202022222424
desktop_font=Nunito Sans Light 12
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=0
show_mounts=0
